name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install rustc and clippy
      uses: actions-rs/toolchain@v1
      with:
         profile: minimal
         toolchain: stable
         override: true
         components: cargo, rustc, clippy
    - name: Linting
      run: cargo clippy -- -D warnings
    - name: Basic tests
      run: env RUST_LOG=debug cargo test
    - name: Python tests
      run: env RUST_LOG=debug cargo test --features=python-bindings,json
